name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  react-app:
    uses: fanatic/actions/.github/workflows/create-react-app.yml@main
    with:
      username: mona
